version: "3"  # optional since v1.27.0
services:
  php:
    container_name: php
    image: waynerichen/php-nginx:8.1-buster
    ports:
        - 80:80        
    volumes:
        - ./html:/var/www/html
    restart: always
