services:
  php:
    container_name: php
    build:
      context: .
      dockerfile: dockerfile/php-8.1/Dockerfile
    ports:
        - 80:80        
    volumes:
        - ./html:/var/www/html
    restart: always
